---
- name: Configure macOS
  hosts: all
  vars_files:
    - config.yml

  tasks:
    - name: Install Homebrew packages
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ homebrew_packages }}"
      tags: [homebrew]

    - name: Install Homebrew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{ homebrew_casks }}"
      tags: [homebrew, casks]

    - name: Tap Homebrew repositories
      community.general.homebrew_tap:
        name: "{{ item }}"
        state: present
      loop: "{{ homebrew_taps }}"
      tags: [homebrew, taps]

    - name: Ensure dotfiles directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/Developer/dotfiles"
        state: directory
        mode: "0755"
      tags: [dotfiles]

    - name: Symlink shell configuration files
      ansible.builtin.file:
        src: "{{ playbook_dir }}/files/{{ item }}"
        dest: "{{ ansible_env.HOME }}/{{ item }}"
        state: link
        force: true
      loop:
        - .zshrc
        - .zprofile
      tags: [dotfiles, shell]

    - name: Symlink git configuration files
      ansible.builtin.file:
        src: "{{ playbook_dir }}/files/{{ item }}"
        dest: "{{ ansible_env.HOME }}/{{ item }}"
        state: link
        force: true
      loop:
        - .gitconfig
        - .gitignore_global
      tags: [dotfiles, git]

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: "0700"
      tags: [ssh]

    - name: Check if .zshrc.local exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.zshrc.local"
      register: zshrc_local
      tags: [dotfiles, secrets]

    - name: Create .zshrc.local from example if not exists
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/.zshrc.local.example"
        dest: "{{ ansible_env.HOME }}/.zshrc.local"
        mode: "0600"
      when: not zshrc_local.stat.exists
      tags: [dotfiles, secrets]

    - name: Ensure VS Code config directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/Library/Application Support/Code/User"
        state: directory
        mode: "0755"
      tags: [vscode]

    - name: Symlink VS Code settings.json
      ansible.builtin.file:
        src: "{{ playbook_dir }}/files/vscode/settings.json"
        dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/settings.json"
        state: link
        force: true
      tags: [vscode]

    - name: Install VS Code extensions
      ansible.builtin.shell: code --install-extension {{ item }}
      loop: "{{ vscode_extensions }}"
      register: vscode_ext_result
      changed_when: "'already installed' not in vscode_ext_result.stdout"
      failed_when: false
      tags: [vscode]

    - name: Install mas (Mac App Store CLI)
      community.general.homebrew:
        name: mas
        state: present
      tags: [mas]

    - name: Install Mac App Store apps
      ansible.builtin.shell: mas install {{ item.id }}
      loop: "{{ mas_apps }}"
      register: mas_result
      changed_when: "'already installed' not in mas_result.stderr"
      failed_when: false
      tags: [mas]

    - name: Remove unwanted bundled apps
      ansible.builtin.shell: mas uninstall {{ item.id }} || true
      loop: "{{ mas_apps_to_remove | default([]) }}"
      failed_when: false
      tags: [mas, cleanup]

    - name: Configure macOS defaults
      community.general.osx_defaults:
        domain: "{{ item.domain }}"
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      loop: "{{ macos_defaults }}"
      when: configure_macos_defaults | default(false)
      tags: [macos]

    # Vaultwarden/Bitwarden secrets integration
    - name: Check if Bitwarden CLI is installed
      ansible.builtin.shell: command -v bw
      register: bw_installed
      failed_when: false
      changed_when: false
      tags: [secrets]

    - name: Install Bitwarden CLI
      community.general.homebrew:
        name: bitwarden-cli
        state: present
      when: bw_installed.rc != 0
      tags: [secrets]

    - name: Check Bitwarden login status
      ansible.builtin.shell: bw status | grep -q '"status":"unlocked"'
      register: bw_unlocked
      failed_when: false
      changed_when: false
      tags: [secrets]

    - name: Fetch secrets from Vaultwarden
      ansible.builtin.shell: |
        bw get password "{{ item.bw_name }}"
      loop: "{{ vaultwarden_secrets | default([]) }}"
      register: fetched_secrets
      when: bw_unlocked.rc == 0
      no_log: true
      tags: [secrets]

    - name: Write secrets to .zshrc.local
      ansible.builtin.template:
        src: templates/zshrc.local.j2
        dest: "{{ ansible_env.HOME }}/.zshrc.local"
        mode: "0600"
      when: bw_unlocked.rc == 0 and fetched_secrets is defined
      tags: [secrets]

    # Sparkle EdDSA signing key
    - name: Check if Sparkle key exists in Keychain
      ansible.builtin.shell: security find-generic-password -s "https://sparkle-project.org" -a "ed25519" 2>/dev/null
      register: sparkle_key_exists
      failed_when: false
      changed_when: false
      tags: [secrets, sparkle]

    - name: Fetch Sparkle private key from Vaultwarden
      ansible.builtin.shell: bw get password "{{ sparkle_key.bw_name }}"
      register: sparkle_private_key
      when:
        - bw_unlocked.rc == 0
        - sparkle_key_exists.rc != 0
        - sparkle_key is defined
      no_log: true
      tags: [secrets, sparkle]

    - name: Add Sparkle key to Keychain
      ansible.builtin.shell: |
        security add-generic-password \
          -s "https://sparkle-project.org" \
          -a "ed25519" \
          -D "private key" \
          -l "Private key for signing Sparkle updates" \
          -w "{{ sparkle_private_key.stdout }}"
      when:
        - sparkle_private_key is defined
        - sparkle_private_key.stdout is defined
        - sparkle_private_key.stdout | length > 0
      no_log: true
      tags: [secrets, sparkle]

    # SSH keys restoration
    - name: Fetch SSH private keys from Vaultwarden
      ansible.builtin.shell: bw get notes "{{ item.bw_name }}"
      loop: "{{ ssh_keys | default([]) }}"
      register: fetched_ssh_keys
      when: bw_unlocked.rc == 0
      no_log: true
      tags: [secrets, ssh]

    - name: Write SSH private keys
      ansible.builtin.copy:
        content: "{{ item.stdout }}"
        dest: "{{ ansible_env.HOME }}/.ssh/{{ ssh_keys[idx].filename }}"
        mode: "0600"
      loop: "{{ fetched_ssh_keys.results | default([]) }}"
      loop_control:
        index_var: idx
      when:
        - item.stdout is defined
        - item.stdout | length > 0
      no_log: true
      tags: [secrets, ssh]

