---
- name: Configure macOS
  hosts: all
  vars_files:
    - config.yml

  roles:
    - role: workspace
      tags: [workspace, repos]

    - role: homebrew
      tags: [homebrew, packages, casks, mas]

    - role: dotfiles
      tags: [dotfiles, shell, git]

    - role: vscode
      tags: [vscode]

    - role: macos
      tags: [macos]
      when: configure_macos_defaults | default(false)

    - role: devtools
      tags: [devtools, ruby, mint, xcode]

    - role: apps
      tags: [apps, betterdisplay]

    - role: secrets
      tags: [secrets, sparkle, ssh]
